on:
  push:
    branches:
      - kubelet
      - vilmos-darwin-cadvisor
name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Build binary
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make WHAT=cmd/kubelet
        env:
          KUBE_BUILD_PLATFORMS: "darwin/amd64"
      - name: Upload kubelet to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          pwd
          ls
          aws s3 cp --acl public-read $(pwd)_output/bin/kubelet s3://procri-dev/kubelet-$GITHUB_RUN_ID
