on:
  push:
    branches:
      - kubelet
      - vilmos-darwin-cadvisor
name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Build binary
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          env KUBE_BUILD_PLATFORMS=darwin/amd64 make WHAT=cmd/kubelet
      - name: Upload kubelet to s3
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp --acl public-read _output/bin/kubelet s3://${{ secrets.AWS_BUCKET }}/kubelet-${{ env.GITHUB_RUN_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
